name: coffee_shop_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^7.1.0
  badges: ^3.1.1
  bloc: ^8.1.1
  cached_network_image: ^3.2.1
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.0
  keyboard_actions: ^4.2.0
  mask_text_input_formatter: ^2.4.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/coffee_background.jpg
